export const player = {
  x: 'X',
  o: 'O',
}

export const actionType = {
  START_NEW_GAME: 'START_NEW_GAME',
  MAKE_MOVE: 'MAKE_MOVE',

  UPDATE_BOARD: 'UPDATE_BOARD',
  UPDATE_WINNER: 'UPDATE_WINNER',
  UPDATE_GAME_ID: 'UPDATE_GAME_ID',
  UPDATE_CUR_PLAYER: 'UPDATE_CUR_PLAYER',
  UPDATE_ERROR_MESSAGE: 'UPDATE_ERROR_MESSAGE',
  UPDATE_IS_TIE: 'UPDATE_IS_TIE',
}

export const BASE_URL = 'http://localhost:5003';